// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/atoms/Icon.vue')['default']
    MyAboutMe: typeof import('./src/components/molecules/MyAboutMe.vue')['default']
    MyHeader: typeof import('./src/components/molecules/MyHeader.vue')['default']
    MyMainProjects: typeof import('./src/components/molecules/MyMainProjects.vue')['default']
    MyParticlesJs: typeof import('./src/components/molecules/MyParticlesJs.vue')['default']
    MyProjects: typeof import('./src/components/molecules/MyProjects.vue')['default']
    MySkills: typeof import('./src/components/molecules/MySkills.vue')['default']
    MySocial: typeof import('./src/components/molecules/MySocial.vue')['default']
    Project: typeof import('./src/components/atoms/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsBlock: typeof import('./src/components/atoms/SkillsBlock.vue')['default']
    SkillTag: typeof import('./src/components/atoms/SkillTag.vue')['default']
    Social: typeof import('./src/components/atoms/Social.vue')['default']
  }
}
